[build]
  base = "prescription-system (2)/prescription-system (2)/prescription-system (2)/prescription-system (2)/prescription-system"
  publish = "frontend/html-css"

[build.environment]
  NODE_VERSION = "18"
